export type Language = 'id' | 'en' | 'ja' | 'zh' | 'es' | 'fr' | 'de' | 'ko' | 'ru' | 'ar' | 'pt' | 'it';

export const LANGUAGES = {
  id: 'Indonesian',
  en: 'English',
  ja: '日本語',
  zh: '中文',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  ko: '한국어',
  ru: 'Русский',
  ar: 'العربية',
  pt: 'Português',
  it: 'Italiano'
} as const;

export type DayKey = 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY';

export type TranslationKey = 
  | 'time'
  | 'theme'
  | 'schedule'
  | 'addClass'
  | 'delete'
  | 'editClass'
  | 'edit'
  | 'changeColor'
  | 'addNewClass'
  | 'className'
  | 'location'
  | 'startTime'
  | 'endTime'
  | 'cancel'
  | 'save'
  | 'update'
  | 'empty'
  | 'dayView'
  | 'weekView'
  | 'free'
  | 'undo'
  | 'redo'
  | 'export'
  | 'search'
  | 'shortcuts'
  | 'language'
  | 'searchPlaceholder'
  | 'classes'
  | 'noClasses'
  | 'addFirstClass'
  | 'previous'
  | 'next'
  | 'today'
  | 'legend'
  | 'classTypes'
  | 'instructor'
  | 'print'
  | 'viewMode'
  | 'selectDay'
  | 'settings'
  | 'menu'
  | 'class'
  | 'classes';

export type TranslationsType = {
  [key in Language]: {
    days: {
      [key in DayKey]: string;
    };
    ui: {
      [key in TranslationKey]: string;
    };
  };
};

export const TRANSLATIONS: TranslationsType = {
  id: {
    days: {
      MONDAY: 'SENIN',
      TUESDAY: 'SELASA',
      WEDNESDAY: 'RABU',
      THURSDAY: 'KAMIS',
      FRIDAY: 'JUMAT',
      SATURDAY: 'SABTU'
    },
    ui: {
      time: 'Waktu',
      theme: 'Tema',
      schedule: 'Jadwal',
      addClass: 'Tambah Kelas',
      delete: 'Hapus',
      editClass: 'Edit Kelas',
      edit: 'Edit',
      changeColor: 'Ubah Warna',
      addNewClass: 'Tambah Kelas Baru',
      className: 'Nama Kelas',
      location: 'Lokasi',
      startTime: 'Waktu Mulai',
      endTime: 'Waktu Selesai',
      cancel: 'Batal',
      save: 'Simpan',
      update: 'Perbarui',
      empty: 'Kosong',
      dayView: 'Tampilan Hari',
      weekView: 'Tampilan Minggu',
      free: 'Kosong',
      undo: 'Batalkan',
      redo: 'Ulangi',
      export: 'Ekspor',
      search: 'Cari',
      shortcuts: 'Pintasan Keyboard',
      language: 'Bahasa',
      searchPlaceholder: 'Cari kelas atau lokasi...',
      classes: 'kelas',
      noClasses: 'Tidak ada kelas terjadwal',
      addFirstClass: 'Tambah Kelas Pertama',
      previous: 'Sebelumnya',
      next: 'Selanjutnya',
      today: 'Hari Ini',
      legend: 'Legenda',
      classTypes: 'Jenis Kelas',
      instructor: 'Pengajar',
      print: 'Cetak',
      viewMode: 'Mode Tampilan',
      selectDay: 'Pilih Hari',
      class: 'kelas',
      classes: 'kelas'
    }
  },
  en: {
    days: {
      MONDAY: 'MONDAY',
      TUESDAY: 'TUESDAY',
      WEDNESDAY: 'WEDNESDAY',
      THURSDAY: 'THURSDAY',
      FRIDAY: 'FRIDAY',
      SATURDAY: 'SATURDAY'
    },
    ui: {
      time: 'Time',
      theme: 'Theme',
      schedule: 'Schedule',
      addClass: 'Add Class',
      delete: 'Delete',
      editClass: 'Edit Class',
      edit: 'Edit',
      changeColor: 'Change Color',
      addNewClass: 'Add New Class',
      className: 'Class Name',
      location: 'Location',
      startTime: 'Start Time',
      endTime: 'End Time',
      cancel: 'Cancel',
      save: 'Save',
      update: 'Update',
      empty: 'Empty',
      dayView: 'Day View',
      weekView: 'Week View',
      free: 'Free',
      undo: 'Undo',
      redo: 'Redo',
      export: 'Export',
      search: 'Search',
      shortcuts: 'Keyboard Shortcuts',
      language: 'Language',
      searchPlaceholder: 'Search classes or locations...',
      classes: 'classes',
      noClasses: 'No classes scheduled',
      addFirstClass: 'Add First Class',
      previous: 'Previous',
      next: 'Next',
      today: 'Today',
      legend: 'Legend',
      classTypes: 'Class Types',
      instructor: 'Instructor',
      print: 'Print',
      viewMode: 'View Mode',
      selectDay: 'Select Day',
      class: 'class',
      classes: 'classes'
    }
  },
  de: {
    days: {
      MONDAY: 'MONTAG',
      TUESDAY: 'DIENSTAG',
      WEDNESDAY: 'MITTWOCH',
      THURSDAY: 'DONNERSTAG',
      FRIDAY: 'FREITAG',
      SATURDAY: 'SAMSTAG'
    },
    ui: {
      time: 'Zeit',
      theme: 'Thema',
      schedule: 'Stundenplan',
      addClass: 'Kurs hinzufügen',
      delete: 'Löschen',
      editClass: 'Kurs bearbeiten',
      edit: 'Edit',
      changeColor: 'Farbe ändern',
      addNewClass: 'Neuen Kurs hinzufügen',
      className: 'Kursname',
      location: 'Ort',
      startTime: 'Startzeit',
      endTime: 'Endzeit',
      cancel: 'Abbrechen',
      save: 'Speichern',
      update: 'Aktualisieren',
      empty: 'Leer',
      dayView: 'Tagesansicht',
      weekView: 'Wochenansicht',
      free: 'Frei',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      export: 'Exportieren',
      search: 'Suchen',
      shortcuts: 'Tastenkombinationen',
      language: 'Sprache',
      searchPlaceholder: 'Kurse oder Orte suchen...',
      classes: 'Kurse',
      noClasses: 'Keine Kurse geplant für',
      addFirstClass: 'Ersten Kurs hinzufügen',
      previous: 'Zurück',
      next: 'Weiter',
      today: 'Heute',
      legend: 'Legende',
      classTypes: 'Kurstypen',
      instructor: 'Dozent',
      print: 'Drucken',
      viewMode: 'Ansichtsmodus',
      selectDay: 'Tag auswählen',
      class: 'kurs',
      classes: 'kurse'
    }
  },
  ko: {
    days: {
      MONDAY: '월요일',
      TUESDAY: '화요일',
      WEDNESDAY: '수요일',
      THURSDAY: '목요일',
      FRIDAY: '금요일',
      SATURDAY: '토요일'
    },
    ui: {
      time: '시간',
      theme: '테마',
      schedule: '시간표',
      addClass: '수업 추가',
      delete: '삭제',
      editClass: '수업 편집',
      edit: 'Edit',
      changeColor: '색상 변경',
      addNewClass: '새 수업 추가',
      className: '수업명',
      location: '위치',
      startTime: '시작 시간',
      endTime: '종료 시간',
      cancel: '취소',
      save: '저장',
      update: '업데이트',
      empty: '비어있음',
      dayView: '일간 보기',
      weekView: '주간 보기',
      free: '공강',
      undo: '실행 취소',
      redo: '다시 실행',
      export: '내보내기',
      search: '검색',
      shortcuts: '단축키',
      language: '언어',
      searchPlaceholder: '수업 또는 위치 검색...',
      classes: '수업',
      noClasses: '예정된 수업이 없습니다',
      addFirstClass: '첫 수업 추가',
      previous: '이전',
      next: '다음',
      today: '오늘',
      legend: '범례',
      classTypes: '수업 유형',
      instructor: '교수',
      print: '인쇄',
      viewMode: '보기 모드',
      selectDay: '요일 선택',
      class: '수업',
      classes: '수업들'
    }
  },
  ru: {
    days: {
      MONDAY: 'ПОНЕДЕЛЬНИК',
      TUESDAY: 'ВТОРНИК',
      WEDNESDAY: 'СРЕДА',
      THURSDAY: 'ЧЕТВЕРГ',
      FRIDAY: 'ПЯТНИЦА',
      SATURDAY: 'СУББОТА'
    },
    ui: {
      time: 'Время',
      theme: 'Тема',
      schedule: 'Расписание',
      addClass: 'Добавить занятие',
      delete: 'Удалить',
      editClass: 'Редактировать занятие',
      edit: 'Edit',
      changeColor: 'Изменить цвет',
      addNewClass: 'Добавить новое занятие',
      className: 'Название занятия',
      location: 'Место',
      startTime: 'Время начала',
      endTime: 'Время окончания',
      cancel: 'Отмена',
      save: 'Сохранить',
      update: 'Обновить',
      empty: 'Пусто',
      dayView: 'По дням',
      weekView: 'По неделям',
      free: 'Свободно',
      undo: 'Отменить',
      redo: 'Повторить',
      export: 'Экспорт',
      search: 'Поиск',
      shortcuts: 'Горячие клавиши',
      language: 'Язык',
      searchPlaceholder: 'Поиск занятий или мест...',
      classes: 'Занятия',
      noClasses: 'Нет занятий на',
      addFirstClass: 'Добавить первое занятие',
      previous: 'Предыдущий',
      next: 'Следующий',
      today: 'Сегодня',
      legend: 'Легенда',
      classTypes: 'Типы занятий',
      instructor: 'Преподаватель',
      print: 'Печать',
      viewMode: 'Режим просмотра',
      selectDay: 'Выбрать день',
      class: 'занятие',
      classes: 'занятия'
    }
  },
  ar: {
    days: {
      MONDAY: 'الاثنين',
      TUESDAY: 'الثلاثاء',
      WEDNESDAY: 'الأربعاء',
      THURSDAY: 'الخميس',
      FRIDAY: 'الجمعة',
      SATURDAY: 'السبت'
    },
    ui: {
      time: 'الوقت',
      theme: 'المظهر',
      schedule: 'الجدول',
      addClass: 'إضافة محاضرة',
      delete: 'حذف',
      editClass: 'تعديل المحاضرة',
      edit: 'Edit',
      changeColor: 'تغيير اللون',
      addNewClass: 'إضافة محاضرة جديدة',
      className: 'اسم المحاضرة',
      location: 'المكان',
      startTime: 'وقت البدء',
      endTime: 'وقت الانتهاء',
      cancel: 'إلغاء',
      save: 'حفظ',
      update: 'تحديث',
      empty: 'فارغ',
      dayView: 'عرض اليوم',
      weekView: 'عرض الأسبوع',
      free: 'متاح',
      undo: 'تراجع',
      redo: 'إعادة',
      export: 'تصدير',
      search: 'بحث',
      shortcuts: 'اختصارات لوحة المفاتيح',
      language: 'اللغة',
      searchPlaceholder: 'البحث عن المحاضرات أو الأماكن...',
      classes: 'المحاضرات',
      noClasses: 'لا توجد محاضرات مجدولة في',
      addFirstClass: 'إضافة أول محاضرة',
      previous: 'السابق',
      next: 'التالي',
      today: 'اليوم',
      legend: 'مفتاح الرموز',
      classTypes: 'أنواع المحاضرات',
      instructor: 'المحاضر',
      print: 'طباعة',
      viewMode: 'وضع العرض',
      selectDay: 'اختر اليوم',
      class: 'محاضرة',
      classes: 'المحاضرات'
    }
  },
  pt: {
    days: {
      MONDAY: 'SEGUNDA',
      TUESDAY: 'TERÇA',
      WEDNESDAY: 'QUARTA',
      THURSDAY: 'QUINTA',
      FRIDAY: 'SEXTA',
      SATURDAY: 'SÁBADO'
    },
    ui: {
      time: 'Horário',
      theme: 'Tema',
      schedule: 'Cronograma',
      addClass: 'Adicionar Aula',
      delete: 'Excluir',
      editClass: 'Editar Aula',
      edit: 'Edit',
      changeColor: 'Mudar Cor',
      addNewClass: 'Adicionar Nova Aula',
      className: 'Nome da Aula',
      location: 'Local',
      startTime: 'Hora de Início',
      endTime: 'Hora de Término',
      cancel: 'Cancelar',
      save: 'Salvar',
      update: 'Atualizar',
      empty: 'Vazio',
      dayView: 'Visualização Diária',
      weekView: 'Visualização Semanal',
      free: 'Livre',
      undo: 'Desfazer',
      redo: 'Refazer',
      export: 'Exportar',
      search: 'Pesquisar',
      shortcuts: 'Atalhos do Teclado',
      language: 'Idioma',
      searchPlaceholder: 'Pesquisar aulas ou locais...',
      classes: 'Aulas',
      noClasses: 'Nenhuma aula agendada para',
      addFirstClass: 'Adicionar Primeira Aula',
      previous: 'Anterior',
      next: 'Próximo',
      today: 'Hoje',
      legend: 'Legenda',
      classTypes: 'Tipos de Aula',
      instructor: 'Professor',
      print: 'Imprimir',
      viewMode: 'Modo de Visualização',
      selectDay: 'Selecionar Dia',
      class: 'aula',
      classes: 'aulas'
    }
  },
  it: {
    days: {
      MONDAY: 'LUNEDÌ',
      TUESDAY: 'MARTEDÌ',
      WEDNESDAY: 'MERCOLEDÌ',
      THURSDAY: 'GIOVEDÌ',
      FRIDAY: 'VENERDÌ',
      SATURDAY: 'SABATO'
    },
    ui: {
      time: 'Orario',
      theme: 'Tema',
      schedule: 'Calendario',
      addClass: 'Aggiungi Lezione',
      delete: 'Elimina',
      editClass: 'Modifica Lezione',
      edit: 'Edit',
      changeColor: 'Cambia Colore',
      addNewClass: 'Aggiungi Nuova Lezione',
      className: 'Nome Lezione',
      location: 'Luogo',
      startTime: 'Ora Inizio',
      endTime: 'Ora Fine',
      cancel: 'Annulla',
      save: 'Salva',
      update: 'Aggiorna',
      empty: 'Vuoto',
      dayView: 'Vista Giornaliera',
      weekView: 'Vista Settimanale',
      free: 'Libero',
      undo: 'Annulla',
      redo: 'Ripeti',
      export: 'Esporta',
      search: 'Cerca',
      shortcuts: 'Scorciatoie da Tastiera',
      language: 'Lingua',
      searchPlaceholder: 'Cerca lezioni o luoghi...',
      classes: 'Lezioni',
      noClasses: 'Nessuna lezione programmata per',
      addFirstClass: 'Aggiungi Prima Lezione',
      previous: 'Precedente',
      next: 'Successivo',
      today: 'Oggi',
      legend: 'Legenda',
      classTypes: 'Tipi di Lezione',
      instructor: 'Docente',
      print: 'Stampa',
      viewMode: 'Modalità di Visualizzazione',
      selectDay: 'Seleziona Giorno',
      class: 'lezione',
      classes: 'lezioni'
    }
  },
  ja: {
    days: {
      MONDAY: '月曜日',
      TUESDAY: '火曜日',
      WEDNESDAY: '水曜日',
      THURSDAY: '木曜日',
      FRIDAY: '金曜日',
      SATURDAY: '土曜日'
    },
    ui: {
      time: '時間',
      theme: 'テーマ',
      schedule: 'スケジュール',
      addClass: '授業追加',
      delete: '削除',
      editClass: '授業編集',
      edit: 'Edit',
      changeColor: '色を変更',
      addNewClass: '新規授業追加',
      className: '授業名',
      location: '場所',
      startTime: '開始時間',
      endTime: '終了時間',
      cancel: 'キャンセル',
      save: '保存',
      update: '更新',
      empty: '空き',
      dayView: '日表示',
      weekView: '週表示',
      free: '空き',
      undo: '元に戻す',
      redo: 'やり直す',
      export: 'エクスポート',
      search: '検索',
      shortcuts: 'キーボードショートカット',
      language: '言語',
      searchPlaceholder: '授業や場所を検索...',
      classes: '授業',
      noClasses: 'この日の授業はありません：',
      addFirstClass: '最初の授業を追加',
      previous: '前',
      next: '次',
      today: '今日',
      legend: '凡例',
      classTypes: '授業タイプ',
      instructor: '講師',
      print: '印刷',
      viewMode: '表示モード',
      selectDay: '曜日選択',
      class: '授業',
      classes: '授業'
    }
  },
  zh: {
    days: {
      MONDAY: '星期一',
      TUESDAY: '星期二',
      WEDNESDAY: '星期三',
      THURSDAY: '星期四',
      FRIDAY: '星期五',
      SATURDAY: '星期六'
    },
    ui: {
      time: '时间',
      theme: '主题',
      schedule: '课程表',
      addClass: '添加课程',
      delete: '删除',
      editClass: '编辑课程',
      edit: 'Edit',
      changeColor: '更改颜色',
      addNewClass: '添加新课程',
      className: '课程名称',
      location: '地点',
      startTime: '开始时间',
      endTime: '结束时间',
      cancel: '取消',
      save: '保存',
      update: '更新',
      empty: '空闲',
      dayView: '日视图',
      weekView: '周视图',
      free: '空闲',
      undo: '撤销',
      redo: '重做',
      export: '导出',
      search: '搜索',
      shortcuts: '键盘快捷键',
      language: '语言',
      searchPlaceholder: '搜索课程或地点...',
      classes: '课程',
      noClasses: '没有安排课程：',
      addFirstClass: '添加第一节课',
      previous: '前一',
      next: '下一',
      today: '今天',
      legend: '图例',
      classTypes: '课程类型',
      instructor: '教师',
      print: '打印',
      viewMode: '查看模式',
      selectDay: '选择日期',
      class: '课程',
      classes: '课程'
    }
  },
  es: {
    days: {
      MONDAY: 'LUNES',
      TUESDAY: 'MARTES',
      WEDNESDAY: 'MIÉRCOLES',
      THURSDAY: 'JUEVES',
      FRIDAY: 'VIERNES',
      SATURDAY: 'SÁBADO'
    },
    ui: {
      time: 'Hora',
      theme: 'Tema',
      schedule: 'Horario',
      addClass: 'Añadir Clase',
      delete: 'Eliminar',
      editClass: 'Editar Clase',
      edit: 'Edit',
      changeColor: 'Cambiar Color',
      addNewClass: 'Añadir Nueva Clase',
      className: 'Nombre de la Clase',
      location: 'Ubicación',
      startTime: 'Hora de Inicio',
      endTime: 'Hora de Fin',
      cancel: 'Cancelar',
      save: 'Guardar',
      update: 'Actualizar',
      empty: 'Vacío',
      dayView: 'Vista Diaria',
      weekView: 'Vista Semanal',
      free: 'Libre',
      undo: 'Deshacer',
      redo: 'Rehacer',
      export: 'Exportar',
      search: 'Buscar',
      shortcuts: 'Atajos de Teclado',
      language: 'Idioma',
      searchPlaceholder: 'Buscar clases o ubicaciones...',
      classes: 'Clases',
      noClasses: 'No hay clases programadas para',
      addFirstClass: 'Añadir Primera Clase',
      previous: 'Anterior',
      next: 'Siguiente',
      today: 'Hoy',
      legend: 'Leyenda',
      classTypes: 'Tipos de Clase',
      instructor: 'Profesor',
      print: 'Imprimir',
      viewMode: 'Modo de Vista',
      selectDay: 'Seleccionar Día',
      class: 'clase',
      classes: 'clases'
    }
  },
  fr: {
    days: {
      MONDAY: 'LUNDI',
      TUESDAY: 'MARDI',
      WEDNESDAY: 'MERCREDI',
      THURSDAY: 'JEUDI',
      FRIDAY: 'VENDREDI',
      SATURDAY: 'SAMEDI'
    },
    ui: {
      time: 'Heure',
      theme: 'Thème',
      schedule: 'Emploi du temps',
      addClass: 'Ajouter un cours',
      delete: 'Supprimer',
      editClass: 'Modifier le cours',
      edit: 'Edit',
      changeColor: 'Changer la Couleur',
      addNewClass: 'Ajouter un nouveau cours',
      className: 'Nom du cours',
      location: 'Lieu',
      startTime: 'Heure de début',
      endTime: 'Heure de fin',
      cancel: 'Annuler',
      save: 'Enregistrer',
      update: 'Mettre à jour',
      empty: 'Vide',
      dayView: 'Vue journalière',
      weekView: 'Vue hebdomadaire',
      free: 'Libre',
      undo: 'Annuler',
      redo: 'Rétablir',
      export: 'Exporter',
      search: 'Rechercher',
      shortcuts: 'Raccourcis clavier',
      language: 'Langue',
      searchPlaceholder: 'Rechercher des cours ou des lieux...',
      classes: 'Cours',
      noClasses: 'Aucun cours prévu pour',
      addFirstClass: 'Ajouter Premier Cours',
      previous: 'Précédent',
      next: 'Suivant',
      today: 'Aujourd\'hui',
      legend: 'Légende',
      classTypes: 'Types de Cours',
      instructor: 'Professeur',
      print: 'Imprimer',
      viewMode: 'Mode d\'affichage',
      selectDay: 'Sélectionner le jour',
      class: 'cours',
      classes: 'cours'
    }
  }
} as const; 